DATABASE:
  DB_USER: medilane
  DB_PASSWORD: 123qweA@
  DB_DRIVER: mysql
  DB_NAME: medilane
  DB_HOST: 66.42.56.107 # 192.168.67.128 #
  DB_PORT: 3306

FCM_KEY : D:\Workspace\medilane\medilane-worker\metadata\medilane-notification-firebase.json
REDIS:
  URL: 66.42.56.107:6379
  DB: 1
  PASSWORD: 098poiA


LOGGER:
  FILE_OUT: ./logs/action.log
  LEVEL: debug
  FORMAT_TEXT: true
  DISABLE_CALLER: false
  SHOW_CALLER: false
  DISABLE_LOG_FILE: false
  DISABLE_CONSOLE_LOG: false
  DISABLE_ROTATE: false
  ROTATE:
    MAX_SIZE: 10
    MAX_BACKUPS: 5
    MAX_DAYS: 5
    COMPRESS: true
    LOCAL_TIME: true